package com.github.alesparza.emulator.gui;

import javax.swing.*;
import java.awt.*;

public class SamplePanel {
  private JPanel samplePanel;
  private JTextField specimenIDTextField;
  private JTextField positionIDTextField;
  private JTextField priorityTextField; // TODO: make it a combobox?
  private JTextField requestDateAndTimeTextField;
  private JTextField collectionDateAndTimeTextField;
  private JTextField receivedDateAndTimeTextField;
  private JTextField specimenTypeTextField;
  private JTextField releasedDateAndTimeTextField;
  private JLabel positionIDLabel;
  private JLabel specimenIDLabel;
  private JLabel priorityLabel;
  private JLabel requestDTLabel;
  private JLabel collectDTLabel;
  private JLabel receiveDTLabel;
  private JLabel completeDTLabel;
  private JLabel specimenTypeLabel;

  public String getReleasedDateAndTime() {
    return releasedDateAndTimeTextField.getText();
  }

  public String getSpecimenType() {
    return specimenTypeTextField.getText();
  }

  public String getReceivedDateAndTime() {
    return receivedDateAndTimeTextField.getText();
  }

  public String getCollectionDateAndTime() {
    return collectionDateAndTimeTextField.getText();
  }

  public String getRequestDateAndTime() {
    return requestDateAndTimeTextField.getText();
  }

  public String getPriority() {
    return priorityTextField.getText();
  }

  public String getPositionID() {
    return positionIDTextField.getText();
  }

  public String getSpecimenID() {
    return specimenIDTextField.getText();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    samplePanel = new JPanel();
    samplePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(9, 3, new Insets(0, 0, 0, 0), -1, -1));
    specimenIDLabel = new JLabel();
    specimenIDLabel.setText("Specimen ID");
    samplePanel.add(specimenIDLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    specimenIDTextField = new JTextField();
    specimenIDTextField.setText("123456789A");
    specimenIDTextField.setToolTipText("Sample ID/Accession Number.  Max characters 22.");
    samplePanel.add(specimenIDTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
    samplePanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    positionIDLabel = new JLabel();
    positionIDLabel.setText("Position ID");
    samplePanel.add(positionIDLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    positionIDTextField = new JTextField();
    positionIDTextField.setText("00001");
    positionIDTextField.setToolTipText("Instrument Position.  Max characters 5.");
    samplePanel.add(positionIDTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
    samplePanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    priorityLabel = new JLabel();
    priorityLabel.setText("Priority");
    samplePanel.add(priorityLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    priorityTextField = new JTextField();
    priorityTextField.setText("R");
    priorityTextField.setToolTipText("Sample Priority.  Must be 'R' or 'S'.");
    samplePanel.add(priorityTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    requestDTLabel = new JLabel();
    requestDTLabel.setText("Request Date and Time");
    samplePanel.add(requestDTLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    requestDateAndTimeTextField = new JTextField();
    requestDateAndTimeTextField.setText("20240101000000");
    requestDateAndTimeTextField.setToolTipText("Ordered D&T.  Must be YYYYMMDDHHMMSS");
    samplePanel.add(requestDateAndTimeTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    collectDTLabel = new JLabel();
    collectDTLabel.setText("Collection Date and Time");
    samplePanel.add(collectDTLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    collectionDateAndTimeTextField = new JTextField();
    collectionDateAndTimeTextField.setText("20240101010000");
    collectionDateAndTimeTextField.setToolTipText("Collected D&T.  Must be YYYYMMDDHHMMSS");
    samplePanel.add(collectionDateAndTimeTextField, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    receiveDTLabel = new JLabel();
    receiveDTLabel.setText("Received Date and Time");
    samplePanel.add(receiveDTLabel, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    receivedDateAndTimeTextField = new JTextField();
    receivedDateAndTimeTextField.setText("20240101020000");
    receivedDateAndTimeTextField.setToolTipText("Lab Receipt D&T.  Must be YYYYMMDDHHMMSS");
    samplePanel.add(receivedDateAndTimeTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    completeDTLabel = new JLabel();
    completeDTLabel.setText("Released Date and Time");
    samplePanel.add(completeDTLabel, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    releasedDateAndTimeTextField = new JTextField();
    releasedDateAndTimeTextField.setText("20240101030000");
    releasedDateAndTimeTextField.setToolTipText("Completed D&T.  Must be YYYYMMDDHHMMSS");
    samplePanel.add(releasedDateAndTimeTextField, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    specimenTypeLabel = new JLabel();
    specimenTypeLabel.setText("Specimen Type");
    samplePanel.add(specimenTypeLabel, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    specimenTypeTextField = new JTextField();
    specimenTypeTextField.setText("Whole Blood");
    specimenTypeTextField.setToolTipText("Specimen Type.  Max characters 21.");
    samplePanel.add(specimenTypeTextField, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    specimenIDLabel.setLabelFor(specimenIDTextField);
    positionIDLabel.setLabelFor(positionIDTextField);
    priorityLabel.setLabelFor(priorityTextField);
    requestDTLabel.setLabelFor(requestDateAndTimeTextField);
    collectDTLabel.setLabelFor(collectionDateAndTimeTextField);
    receiveDTLabel.setLabelFor(receivedDateAndTimeTextField);
    completeDTLabel.setLabelFor(releasedDateAndTimeTextField);
    specimenTypeLabel.setLabelFor(specimenTypeTextField);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return samplePanel;
  }


  // TODO: connect to console logger

  // TODO: make all date/time fields choosers, but only send correct format back
}
